[2023-10-16T22:49:52.654-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first.process manual__2023-10-17T03:49:47.648069+00:00 [queued]>
[2023-10-16T22:49:52.661-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first.process manual__2023-10-17T03:49:47.648069+00:00 [queued]>
[2023-10-16T22:49:52.661-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-16T22:49:52.676-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process> on 2023-10-17 03:49:47.648069+00:00
[2023-10-16T22:49:52.679-0500] {standard_task_runner.py:57} INFO - Started process 16270 to run task
[2023-10-16T22:49:52.683-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'first', 'process', 'manual__2023-10-17T03:49:47.648069+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/tmp/tmpc1c0kdxv']
[2023-10-16T22:49:52.683-0500] {standard_task_runner.py:85} INFO - Job 12: Subtask process
[2023-10-16T22:49:52.713-0500] {task_command.py:416} INFO - Running <TaskInstance: first.process manual__2023-10-17T03:49:47.648069+00:00 [running]> on host dexne
[2023-10-16T22:49:52.846-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='first' AIRFLOW_CTX_TASK_ID='process' AIRFLOW_CTX_EXECUTION_DATE='2023-10-17T03:49:47.648069+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-17T03:49:47.648069+00:00'
[2023-10-16T22:49:52.847-0500] {first.py:25} INFO - performing processing
[2023-10-16T22:49:52.847-0500] {python.py:194} INFO - Done. Returned value was: None
[2023-10-16T22:49:52.850-0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=first, task_id=process, execution_date=20231017T034947, start_date=20231017T034952, end_date=20231017T034952
[2023-10-16T22:49:52.895-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-16T22:49:52.934-0500] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
